name: Code-review

on: [pull_request]

jobs:
  install:
    name: Installing packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          registry-url: https://npm.pkg.github.com/
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true' # It will run install dependencies just if hash of yarn.lock changed
        run: yarn install --frozen-lockfile --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGES_TOKEN }}

  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          registry-url: https://npm.pkg.github.com/
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Get Diff Action
        id: git-diff
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: +(src)/**/*.+(js|ts|jsx|tsx)

      - name: Lint Diff Files
        run: yarn eslint ${{ steps.git-diff.outputs.diff }}

  deadcode:
    name: Find dead code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          registry-url: https://npm.pkg.github.com/
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Find dead code
        run: yarn ts-prune --error

  # @TODO: allow to testing after adjust all unit tests.
  # testing:
  #   name: Unit testing
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Restore node_modules
  #       uses: actions/cache@v2
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

  #     - name: Use Node.js 14.17.0
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.17.0'
  #         registry-url: https://npm.pkg.github.com/
  #         cache: 'yarn'
  #         cache-dependency-path: '**/yarn.lock'

  #     - name: Run unit tests
  #       run: yarn test
