name: Release
on:
  push:
    branches:
      - main

  # pull_request:
  #   branches:
  #     - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.0'
          registry-url: https://npm.pkg.github.com/

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true' # It will run install dependencies just if hash of yarn.lock changed
        run: yarn install --frozen-lockfile --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGES_TOKEN }}

      - name: Build CJS
        run: yarn build:cjs

      - name: Build ESM
        run: yarn build:esm

      - name: Create Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Update Github Name
        run: git config user.name TradersClubCI

      - name: Update Github Email
        run: git config user.email tradersclub.com.br@gmail.com

      - name: Commit Updated Version
        run: npm version ${{ steps.tag_version.outputs.new_version }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGES_TOKEN }}

      # - name: Send message to Slack API
      #   uses: archive/github-actions-slack@v2.0.0
      #   with:
      #     slack-bot-user-oauth-access-token: ${{ secrets.RELEASE_SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
      #     slack-channel: C01S0JCEUSU
      #     slack-text: '*Nova versão ${{ steps.tag_version.outputs.release_type }} ${{ steps.tag_version.outputs.new_tag }} do TCDesignSystem* :rocket:\n\n${{ steps.tag_version.outputs.changelog }}'
      #     slack-optional-icon_emoji: ':fire:'
